name: CI

on:
  pull_request:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'
      - '*-dev'
  push:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'
      - '*-dev'

jobs:
  lint:
    uses: aaronmallen/activeinteractor/.github/workflows/lint.yml@2-0-dev
  test:
    uses: aaronmallen/activeinteractor/.github/workflows/test.yml@2-0-dev
    secrets:
      cc-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
  build:
    uses: aaronmallen/activeinteractor/.github/workflows/build_gem.yml@2-0-dev
